### ISSUE TITLE
Documentation Tracker

### ISSUE THREAD

**Issue by sbshah97** [Hrily/ZBot#1]
Documentation should cover the following points:
- [ ] How to setup environment?
- [ ] Language version 
- [ ] How to run the code?
- [ ] Accompanying libraries and frameworks
- [ ] A CONTRIBUTING.md document
